name: Deployment

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.PET_KEY }}

      - name: Install
        run: npm install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PET_KEY }}
          publish_dir: ./dist
